apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  namespace: task-manager
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:16
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: task-manager-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: task-manager-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: task-manager-secrets
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: task-manager
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
